apiVersion: apps/v1
kind: Deployment
metadata:
  name: python
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python
        image: docker.io/samahalisaber/python-task:v1.2
        ports:
        - containerPort: 8080
